export enum AlertType {
  BUDGET_THRESHOLD = 'BUDGET_THRESHOLD',
  HIGH_RESERVATION = 'HIGH_RESERVATION',
  PERIOD_ENDING = 'PERIOD_ENDING',
  ACCOUNT_FROZEN = 'ACCOUNT_FROZEN',
  ACCOUNT_CLOSED = 'ACCOUNT_CLOSED',
  SPEND_FAILED = 'SPEND_FAILED',
  ADMIN_TRANSFERRED = 'ADMIN_TRANSFERRED',
  CONTRACT_PAUSED = 'CONTRACT_PAUSED',
  CONTRACT_UNPAUSED = 'CONTRACT_UNPAUSED',
  LOW_TREASURY_BALANCE = 'LOW_TREASURY_BALANCE',
}
